name: Actitvity Events
on: 
  pull_request:
    types: opened
  workflow_dispatch:
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps: 
    - name: get code
      uses: actions/checkout@v5
    - name: install dependencies
      run: npm ci
    - name: Test and Build
      run: npm run test
      run: npm run build
    - name: Deploy
      run: echo "Deploying..."