name: Lint Pipeline
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        run: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
  testandbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        run: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Success
        run: echo "Success"
