name: Lint Pipeline
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.set-output-step.outputs.number }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Generate Build Number
        id: set-output-step
        rum: echo "number=12345" >> $GITHUB_OUTPUT
  testandbuild:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-Build
          path: |
            dist
            package.json
      - name: Print Build Number
        run: echo "Deploying build ${{ needs.lint.outputs.build-number}}"
      - name: Success
        run: echo "Success"
  deploy:
    needs: testandbuild
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Frontend-Build
      - name: output content
        run: ls
      - name: Deploy
        run: echo "Deploying..."
