name: Lint Pipeline
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
  testandbuild:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publush.outputs.file-name }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'file-name={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-Build
          path: |
            dist
            package.json
      - name: Success
        run: echo "Success"
  deploy:
    needs: testandbuild
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Frontend-Build
      - name: output content
        run: ls
      - name: Output Filename
        run: echo "${{ needs.build.outputs.file-name }}"
      - name: Deploy
        run: echo "Deploying..."
