name: Lint Pipeline
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Set output version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  testandbuild:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-Build
          path: |
            dist
            package.json
      - name: Print Version Number
        run: echo "Version Number ${{ needs.lint.outputs.version}}"
      - name: Success
        run: echo "Success"
  deploy:
    needs: testandbuild
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Frontend-Build
      - name: output content
        run: ls
      - name: Deploy
        run: echo "Deploying..."
