name: Test And Deploy
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "src/main.jsx"
  workflow_dispatch:
  pull_request:
    types: [closed, opened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo Code
        uses: actions/checkout@v5
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build
      - name: Deploy
        run: echo "Deploying..........."
